<?php

namespace IHM\CovoiturageBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdvertsPage($page, $nbAdParPage)
    {
        $query = $this->createQueryBuilder('a')->orderBy('a.date', 'DESC')->getQuery();
        
        $query->setFirstResult(($page-1) * $nbAdParPage)->setMaxResults($nbAdParPage);
        
        return new Paginator($query, true);
    }
    
    public function getAdvertsParVilles($villeD, $villeA)
    {
        $query = $this
            ->createQueryBuilder('a')
            ->where('a.villeArrivee = :ville_arrivee')
                ->setParameter('ville_arrivee', $villeA)
            ->andWhere('a.villeDepart = :ville_depart')
                ->setParameter('ville_depart', $villeD)
            ->getQuery();
        
        return $query->getResult();
    }
    
}
