<?php

namespace IHM\CovoiturageBundle\Repository;

/**
 * InscripCovoitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscripCovoitRepository extends \Doctrine\ORM\EntityRepository
{
}
