<?php

namespace IHM\CovoiturageBundle\Repository;

/**
 * VilleArriveeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleArriveeRepository extends \Doctrine\ORM\EntityRepository
{
}
