<?php

namespace IHM\CovoiturageBundle\Repository;

/**
 * VilleDepartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleDepartRepository extends \Doctrine\ORM\EntityRepository
{
}
